# Generated by scripts/publish-package-repos.js — do not edit by hand.
cask "myhomegames-server" do
  version "1.1.0"

  if Hardware::CPU.arm?
    sha256 "4f97af53d467f8545d0bd04dc672595172a3860c78f346a3f556a9670ee2b584"
    url "https://github.com/myhomegames/myhomegames-server/releases/download/1.1.0/MyHomeGames-1.1.0-mac-arm64.pkg"
  else
    sha256 "9782e3586b6a81518f62d389beb438c7110c9338a00301747b68de7ad8b62bbe"
    url "https://github.com/myhomegames/myhomegames-server/releases/download/1.1.0/MyHomeGames-1.1.0-mac-x64.pkg"
  end

  name "MyHomeGames Server"
  desc "Self-hosted game library server"
  homepage "https://myhomegames.vige.it"

  pkg "MyHomeGames-#{version}-mac-#{Hardware::CPU.arm? ? 'arm64' : 'x64'}.pkg"

  uninstall pkgutil: "com.myhomegames.server"
end
