# Generated by scripts/publish-package-repos.js — do not edit by hand.
cask "myhomegames-server" do
  version "1.1.0"

  if Hardware::CPU.arm?
    sha256 "4f225d8cef42f45a45543f67799cead30605a7dc661b238b8ee099c72e8f2ba3"
    url "https://github.com/myhomegames/myhomegames-server/releases/download/1.1.0/MyHomeGames-1.1.0-mac-arm64.pkg"
  else
    sha256 "ecee1e638296a658366a57187b808483fa0024900cf2ee19a774408d2c2416db"
    url "https://github.com/myhomegames/myhomegames-server/releases/download/1.1.0/MyHomeGames-1.1.0-mac-x64.pkg"
  end

  name "MyHomeGames Server"
  desc "Self-hosted game library server"
  homepage "https://myhomegames.vige.it"

  pkg "MyHomeGames-#{version}-mac-#{Hardware::CPU.arm? ? 'arm64' : 'x64'}.pkg"

  uninstall pkgutil: "com.myhomegames.server"
end
